### ISSUE TITLE
Feature request: encrypt/decrypt a text

### ISSUE THREAD

**Issue by mukilarasan101** [chrisenytc/alphonse#1]
Hi , 
Can you please give the support to encrypt/decrypt the text instead of file?

example:

> iex(1)> {:ok, security_val} = Alphonse.encryptText "hello world\n", "testiekeyphraseforcipher","testieivphraseforcipher"
> iex(2)> security_val
> "71UcZPQnuKi4JbLSNoEEUw%3D%3D"
> iex(3)> {:ok, val}=Alphonse.decrypt "71UcZPQnuKi4JbLSNoEEUw%3D%3D", "testiekeyphraseforcipher", "testieivphraseforcipher"
> iex(4)> val
> "hello world\n"

**Comment by chrisenytc** [comment]
Hi @mukilarasan101, this feature already exist. See the `encrypt_source` and `decrypt_source`
